# Generated by Django 5.0.7 on 2025-02-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['delivered']},
        ),
    ]
